### ISSUE TITLE
We need to record all user calculations made in the calculator API to serve as history.

### ISSUE THREAD

**Issue by lucaswunder** [bryancosta776/CalculatorBackEnd#18]

**Comment by bryancosta776** [comment]
Por que não usar SQL?

- O SQL é uma estrutra de linguagem de consulta, pode ser poderoso, mas é mais indicado para dados onde se deve ter uma estrutura pré-definida já feita, isso automaticamente o torna mais restritivo e como estamos procurando somente devolver os valores dos resultados das equações, não torna obrigatório o uso de tal. O uso de SQL não estaria errado se fosse inserido no lugar do NoSQL, mas isso seria um tempo a mais gasto em uma tarefa que não precisa ser tão complexa para ser feita. Se fossemos usar uma estrutura mais complexa de dados, o correto seria usar o mysql pelo fato de ser mais restritivo, e com uma estrutura pré-definida, automaticamente o torna mais seguro. A base de dados SQL podem se tornar menos escaláveis pelo fato de que necessita de que o servidor seja carregado para que as informações sejam carregadas, automaticamente, seria necessário uma que seja mais poderosa em questões de capacidade de RAM e operacional, ou seja, o custo se torna maior. Outro ponto que podemos considerar é que o mysql é um banco relacional, ou seja, se utilizássemos tal banco, teriamos que devolver uma tabela de dados, o que não é necessário pois temos que devolver somente o histórico de das equações.

O que estamos ganhando usando NoSQL? 

O principal ganho que estamos tendo usando o NoSQL é o tempo e escalabilidade. Como vamos ter valores numéricos retornando, não precisamos ter uma tabela pré-definida para inserir, o que pode ser mais produtivo, pois se temos menos complexidade na hora de desenvolver um banco de dados, isso automaticamente nos da mais tempo para desenvolver melhoras a API. O banco de dados NoSQL nos permite processar grandes volumes de dados que não estão pré-definidos e isso se torna algo positivo pelo fato de que se alguma hora quisermos expandir as funcionalidades da API da calculadora, o processamento desses dados será melhor. Ganhamos tempo com o NoSQL, pois como ele não tem uma estrutura pré-definida, não precisamos ficar navegando em arquiteturas SQL para achar dados na memória do banco.


Por que o MongoDB? 

Vou usar o MongoDB pela familiaridade com o banco de dados e pelo motivo de ele aguentar grande volumes de dados, isso quer dizer que ele pode armazenar grande quantidade de dados, mas não quer dizer que os dados vão ser pesados. Outra boa ferramenta que podemos usar fazendo o uso do MongoDB, é o mongoose, ele vai mapear meu banco de dados em objetos Javascript para que se eu quiser fazer o uso desses dados em algum momento, posso inseri-los na minha aplicação.
